### ISSUE TITLE
Implementation Problem

### ISSUE THREAD

**Issue by yc1999** [231sm/Reasoning_In_EE#2]
Thank u for ur sharing! In your paper, there are three modules discussed：

![model](https://img-blog.csdnimg.cn/20210624092705335.png)

1. `Event Detection`
2. `Event Ontology Learning`
3. `Event Correlation Inference`

However, in this repository, I can only find the implementaion of `Event Detection`. Did I overlook the other two modules' implementation or you forgot to upload them?

**Comment by 231sm** [comment]
We will upload the full project recently, thank you for reminding us!
