### ISSUE TITLE
about the test dataset and prediction

### ISSUE THREAD

**Issue by takemars** [231sm/Reasoning_In_EE#4]
I want to know how to make test dataset if i test in a new dataset. In addition,is there a separate code for prediction? Thanks.

**Comment by 231sm** [comment]
Thanks for your attention to our work! 

If you would like to test in a new dataset, you can handle it by following the data_utils.py, and formulate your own dataset to the same input format of OntoEvent. 

We have integrated training, validation, and testing process in a main() function at run_ontoed.py. If you want to separate code for prediction, you can input --do_train and --do_eval only without --do_test when you run the model, and solely test with --do_test input. Or you can disentangle our code for training, validation, and testing respectively.

**Comment by takemars** [comment]
Thank you very much for your reply.
