### ISSUE TITLE
about train dataset

### ISSUE THREAD

**Issue by takemars** [231sm/Reasoning_In_EE#5]
When I was testing, I found that if a sentence does not contain any event, but the prediction result is given as belonging to a certain event type, it turns out that the training set is for sentences that contain events, but how should sentences that do not contain events be added to the training set? What values should be filled in the trigger and trigger_pos fields? After adding the sentences without event type, what other changes should be made?

**Comment by 231sm** [comment]
Thank you very much for continous attention to our work! 

Based on your issue#4 proposed yesterday, I guess you have tested our model on your own dataset, as the question you proposed doesn't exist in our OntoEvent. 

For your Q1: if sentences do not contain events, they can also be added to the training set, so long as you add a "none" event type. 

For your Q2: no trigger doesn't mean no event type, and triggers are not necessary for event types.

For your Q3: You can add a "none" event type.

Last but not least, if you have any further question, you can send an E-mail to me, and my E-mail address is 231sm@zju.edu.cn. We can even chat from E-mail to WeChat, for more efficient communication. 
Good night!
