### ISSUE TITLE
question about trigger identification

### ISSUE THREAD

**Issue by Macvh** [231sm/Reasoning_In_EE#6]
您好，我在代码中没找到关于触发词识别的部分，在模型部分我只找到使用instance_embedding来进行事件分类，我不太清楚是不是我对代码理解有误，请问您是怎么进行触发词识别的，以及相应的评价指标是怎么计算的

**Comment by 231sm** [comment]
您好，非常感谢您对我们工作的关注！

您的问题很好，您对代码的理解也相当到位，触发词识别这部分代码我们暂时没有直接集成在OntoED模型中，因为它实现比较简单，可以直接用BERT+CRF实现，您可以参考https://github.com/THU-KEG/MAVEN-dataset/tree/main/baselines/BERT%2BCRF/BERT-CRF-MAVEN 进行复现。

再次感谢您对我们工作的关注！如果实现方面有什么问题，您可以邮件联系我：231sm@zju.edu.cn，祝好！

**Comment by Macvh** [comment]
好的，非常感谢您的回复
