### ISSUE TITLE
请问模型适用于中文事件抽取吗

### ISSUE THREAD

**Issue by TinaGioro** [231sm/Reasoning_In_EE#7]
你好，粗略拜读了您的论文，但发现都是在英文集上做实验，请问适用于中文集吗，如果可以需要修改哪些地方呢

**Comment by 231sm** [comment]
您好，非常感谢您对我们工作的关注！
是的，目前我们都是在英文EE数据集上做的实验，理论上是可以用于中文的，您可以用一些中文的EE数据集做一下尝试，比如DuEE等
修改的地方，主要涉及（1）输入，需要保证输入数据集的格式和OntoEvent的格式相符合，这个我们在readme里有做详细说明；（2）LABEL_PATH，需要把最后的标签集合设置成你所要分类的中文事件类型集合
