### ISSUE TITLE
Sharing Trained Model Weights

### ISSUE THREAD

**Issue by shakib-root** [231sm/Reasoning_In_EE#8]
Could you kindly share the trained model weights?

**Comment by 231sm** [comment]
Hello, thank you very much for your interest in our work. 
This work is in cooperation with the enterprise. The open code has gone through the publishing process. Generally, the company is not allowed to directly open the model. We are very sorry for this, but you can train the model on your own by following the README.md provided by us, which is also very convenient. If you have any problem when training the model, you can contact us.

**Comment by shakib-root** [comment]
@231sm Thank you. I didn't have any problems while training. I was wondering if there is any inference script that allows passing a single document/article and getting the prediction results.

**Comment by 231sm** [comment]
@shakib-root Hello, thank you very much for your continuous attention to our work.
We haven't provided an inference script for document-level event detection, as our paper doesn't aim at this task. 
It will be a significant extension if you try the document-level event detection task based on our code. In theory, it will work. I am looking forward to your good news on this extension.

**Comment by shakib-root** [comment]
@231sm yes, my goal is somewhat in the direction of document-level event detection. In that case, is there any inference code available for sentence-level ED that can be run with a trained model?

**Comment by 231sm** [comment]
@shakib-root Hello, I advise that you can select some trained document-level ED models directly, as sentence-level ED and document-level ED has different training goals and loss function.
